# Load environment configuration first
[ -f "$HOME/.config/dir_colors" ] && eval `dircolors "$HOME/.config/dir_colors"`
[ -f "$HOME/.profile" ] && source "$HOME/.profile"
[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ] && source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
[ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ] && source "$HOME/.nix-profile/etc/profile.d/nix.sh"
[ -f "$HOME/.nix-profile/etc/profile.d/nix-daemon.sh" ] && source "$HOME/.nix-profile/etc/profile.d/nix-daemon.sh"
export "NIX_PATH=${NIX_PATH:-$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH}"

# Don't create .zcompdump files in $HOME
compinit -d "${XDG_CACHE_HOME}/zsh/zcompdump-${ZSH_VERSION}"

# Everything else is just for interactive shells
if [[ -o interactive ]]; then
    # Start screen if...
    if \
        # The command exists \
        (( $+commands[screen] )) && \
            # The configuration file exists \
            [ -f "$XDG_CONFIG_HOME/screen/config" ] && \
            # Screen is not already running \
            [ -z "$STY" ] && \
            # And our terminal is acceptable \
            [ "$TERM" != "dumb" ] && \
            [ "$TERM" != "linux" ]; then
        exec screen -AxRR -c "$XDG_CONFIG_HOME/screen/config"
    fi

    # Load zsh configuration
    ZDOTDIR="$XDG_CONFIG_HOME/zsh"
    source "$ZDOTDIR/zshrc"
fi
