# Load environment configuration first
[ -f "$HOME/.config/dir_colors" ] && eval `dircolors "$HOME/.config/dir_colors"`
[ -f "$HOME/.profile" ] && source "$HOME/.profile"

# Start screen if it hasn't started yet
if (( $+commands[screen] )) && [ -z "$STY" ] && [ "$TERM" != "dumb" ] && [ "$TERM" != "linux" ]; then
    echo $TERM
    exec screen -AxRR
fi

# Load zsh configuration
ZDOTDIR="$XDG_CONFIG_HOME/zsh"
source "$ZDOTDIR/zshrc"
