keys:
  - &tlater 8322CC1D351D8EFE63F3 D27A8CF496E6E265C6A3!
  - &yui age1fk5u7h30pwmnzs6hnrzjxfuzzvkpplas43mq8vtem95hnydrfu9q4f9s5a
  - &tlater-famedly E3A01E05CDB7D42E9909 B9394D863FBF16FE6D51
  - &rin age1qne0ry5pxn4pfqzney9hxy9dedst02qtvfrmnf2p7dhr560mgcusg3tpz6

creation_rules:
  - key_groups:
      - pgp:
          - *tlater
        age:
          - *yui
  - path_regex: secrets/work/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
          - *tlater-famedly
        age:
          - *rin
