config:
  backup: true
  create: true
  dotpath: dotfiles

profiles:
  ren:
    dotfiles:
      - ALL

dotfiles:
  bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
    link: true
  bashrc:
    dst: ~/.bashrc
    src: bashrc
    link: true
  screenrc:
    dst: ~/.screenrc
    src: screenrc
    link: true
  stumpwm:
    dst: ~/.config/stumpwm
    src: stumpwm
    link: true
  xbindkeysrc:
    dst: ~/.xbindkeysrc
    src: xbindkeysrc
    link: true
  Xresources:
    dst: ~/.Xresources
    src: Xresources
    link: true
  termite:
    dst: ~/.config/termite/config
    src: termiterc
    link: true
  gtk3:
    dst: ~/.config/gtk-3.0
    src: gtk/gtk-3.0
    link: true
  gtk2:
    dst: ~/.gtkrc-2.0
    src: gtk/gtkrc-2.0
    link: true
  git:
    dst: ~/.gitconfig
    src: gitconfig
    link: true
  fontconfig:
    dst: ~/.config/fontconfig/fonts.conf
    src: fonts.conf
    link: true
  systemd-user:
    dst: ~/.config/systemd/user
    src: systemd-user
    link: true
  ncmpcpp:
    dst: ~/.config/ncmpcpp
    src: ncmpcpp
    link: true
  mpd:
    dst: ~/.config/mpd
    src: mpd
    link: true


 # emacs:
 #   actions:
 #     - install_prelude

#actions:
#  install_emacs:
#    curl -LO https://github.com/bbatsov/prelude/raw/master/utils/installer.sh;
#    chmod +x installer.sh
#    bash installer.sh
#    rm installer.sh
#    ln -s $HOME/.emacs.d/personal emacs.d/personal
#    ln -s $HOME/.emacs.d/prelude-modules.el emacs.d/prelude-modules.el
