[bauer]
src.github_tag = "matthewbauer/bauer"
fetch.github = "matthewbauer/bauer"

[deepfilternet]
src.github = "Rikorose/DeepFilterNet"
fetch.github = "Rikorose/DeepFilterNet"

[drivestrike]
src.cmd = "./get-drivestrike-version.sh"
fetch.url = "https://app.drivestrike.com/static/yum/drivestrike.rpm"

[firefox-ui-fix]
src.git = "https://github.com/black7375/Firefox-UI-Fix"
# For the time being, until this project figures out its releasening
src.branch = "master"
fetch.github = "black7375/Firefox-UI-Fix"

[gauth]
src.github_tag = "pcarrier/gauth"
fetch.github = "pcarrier/gauth"

[gcs]
src.github = "richardwilkes/gcs"
fetch.github = "richardwilkes/gcs"

[ohmyzsh]
src.git = "https://github.com/ohmyzsh/ohmyzsh"
src.branch = "master"
fetch.github = "ohmyzsh/ohmyzsh"

[phosphor-icons]
src.git = "https://github.com/phosphor-icons/web"
src.branch = "master"
fetch.github = "phosphor-icons/web"

[tridactyl-emacs]
src.git = "https://github.com/jumper047/tridactyl_emacs_config"
src.branch = "main"
fetch.github = "jumper047/tridactyl_emacs_config"
