[bauer]
src.github_tag = "matthewbauer/bauer"
fetch.github = "matthewbauer/bauer"

[catppuccin-alacritty]
src.git = "https://github.com/catppuccin/alacritty"
fetch.github = "catppuccin/alacritty"

[catppuccin-fuzzel]
src.git = "https://github.com/catppuccin/fuzzel"
fetch.github = "catppuccin/fuzzel"

[catppuccin-i3]
src.github = "catppuccin/i3"
fetch.github = "catppuccin/i3"

[delta-icons]
src.github = "Delta-Icons/android"
fetch.github = "Delta-Icons/android"

[drivestrike]
src.cmd = "nu ./get-drivestrike-version.nu"
fetch.url = "https://app.drivestrike.com/static/yum/drivestrike.rpm"

[eglot-x]
src.git = "https://github.com/nemethf/eglot-x"
fetch.github = "nemethf/eglot-x"

[edopro]
src.git = "https://github.com/edo9300/edopro.git"
fetch.github = "edo9300/edopro"
git.fetchSubmodules = true

[edopro-assets]
src.webpage = "https://projectignis.github.io/download.html"
src.regex = 'https://github\.com/ProjectIgnis/edopro-assets/releases/download/(?P<version>\d+\.\d+\.\d+)/ProjectIgnis-EDOPro-\1-linux\.tar\.gz'
fetch.tarball = "https://github.com/ProjectIgnis/edopro-assets/releases/download/$ver/ProjectIgnis-EDOPro-$ver-linux.tar.gz"

[edopro-irrlicht]
src.git = "https://github.com/edo9300/irrlicht1-8-4.git"
fetch.github = "edo9300/irrlicht1-8-4"

[kdl-mode]
src.git = "https://github.com/taquangtrung/emacs-kdl-mode"
fetch.github = "taquangtrung/emacs-kdl-mode"

[nvidia]
src.webpage = "https://www.nvidia.com/en-us/drivers/unix/"
src.regex = "Latest Production Branch Version:</span> *<a href=.*?> *(.*?) *</a>"
fetch.url = "https://us.download.nvidia.com/XFree86/Linux-x86_64/$ver/NVIDIA-Linux-x86_64-$ver.run"

[nvidia-open]
src.webpage = "https://www.nvidia.com/en-us/drivers/unix/"
src.regex = "Latest Production Branch Version:</span> *<a href=.*?> *(.*?) *</a>"
fetch.github = "NVIDIA/open-gpu-kernel-modules"

[ocgcore]
src.github = "edo9300/ygopro-core"
fetch.github = "edo9300/ygopro-core"

[firefox-ui-fix]
src.github = "black7375/Firefox-UI-Fix"
fetch.github = "black7375/Firefox-UI-Fix"

[gcs]
# src.github = "richardwilkes/gcs"
src.manual = "v5.27.0"
fetch.github = "richardwilkes/gcs"

[phosphor-icons]
src.git = "https://github.com/phosphor-icons/web"
src.branch = "master"
fetch.github = "phosphor-icons/web"
