[bauer]
src.github_tag = "matthewbauer/bauer"
fetch.github = "matthewbauer/bauer"

[deepfilternet]
src.github = "Rikorose/DeepFilterNet"
fetch.github = "Rikorose/DeepFilterNet"

[drivestrike]
src.cmd = "./get-drivestrike-version.sh"
fetch.url = "https://app.drivestrike.com/static/yum/drivestrike.rpm"

[eglot-x]
src.git = "https://github.com/nemethf/eglot-x"
fetch.github = "nemethf/eglot-x"

[edopro]
src.git = "https://github.com/edo9300/edopro.git"
fetch.github = "edo9300/edopro"
git.fetchSubmodules = true

[edopro-assets]
src.webpage = "https://projectignis.github.io/download.html"
src.regex = 'https://github\.com/ProjectIgnis/edopro-assets/releases/download/(?P<version>\d+\.\d+\.\d+)/ProjectIgnis-EDOPro-\1-linux\.tar\.gz'
fetch.tarball = "https://github.com/ProjectIgnis/edopro-assets/releases/download/$ver/ProjectIgnis-EDOPro-$ver-linux.tar.gz"

[edopro-irrlicht]
src.git = "https://github.com/edo9300/irrlicht1-8-4.git"
fetch.github = "edo9300/irrlicht1-8-4"

[ocgcore]
src.github = "edo9300/ygopro-core"
fetch.github = "edo9300/ygopro-core"

[firefox-ui-fix]
src.github = "black7375/Firefox-UI-Fix"
fetch.github = "black7375/Firefox-UI-Fix"

[gauth]
src.github_tag = "pcarrier/gauth"
fetch.github = "pcarrier/gauth"

[gcs]
# src.github = "richardwilkes/gcs"
src.manual = "v5.27.0"
fetch.github = "richardwilkes/gcs"

[ohmyzsh]
src.git = "https://github.com/ohmyzsh/ohmyzsh"
src.branch = "master"
fetch.github = "ohmyzsh/ohmyzsh"

[phosphor-icons]
src.git = "https://github.com/phosphor-icons/web"
src.branch = "master"
fetch.github = "phosphor-icons/web"
