{ config, lib, ... }:
{
  imports = [
    ./extensions.nix
    ./lepton.nix
  ];

  programs.librewolf = {
    enable = true;

    languagePacks = [
      "af"
      "de"
      "en-US"
      "nl"
      "zh-CH"
    ];

    settings = {
      # Disable an annoying pop-up
      "browser.protections_panel.infoMessage.seen" = true;
      # Don't quit the browser on C-q
      "browser.quitShortcut.disabled" = true;
      # Open last browser session on startup
      "browser.startup.page" = 3;
      # Don't show the bookmark toolbar
      "browser.toolbars.bookmarks.visibility" = "never";
      # Use OS locale (for time, date, etc.)
      "intl.regional_prefs.use_os_locales" = true;
      # Generally disable WebGL; this is the default setting, but I
      # regularly need to globally enable WebGL. This resets it on
      # browser launch.
      #
      # TODO(tlater): Wait for
      # https://codeberg.org/librewolf/issues/issues/1917
      "webgl.disabled" = true;
    };
  };

  # Force using `pref` instead of `defaultPref`
  home.file.".librewolf/librewolf.overrides.cfg".text =
    let
      inherit (config.programs.librewolf) settings;
    in
    lib.mkIf (settings != { }) (
      lib.mkForce ''
        // Generated by Home Manager.

        ${lib.concatMapAttrsStringSep "\n" (n: v: ''pref("${n}", ${builtins.toJSON v})'') settings}
      ''
    );
}
