# Ensure we follow XDG_BASE_DIRECTORY specifications
HISTFILE="$XDG_DATA_HOME/.zsh_history"

# Load extensions
autoload -U zcalc

# Allow nix-shell to function
if (( $+commands[any-nix-shell] )); then
    any-nix-shell zsh | source /dev/stdin
fi

# Activate direnv
eval "$(direnv hook zsh)"

# Load more granular configuration files
source "$ZDOTDIR/functions.zsh"
source "$ZDOTDIR/aliases.zsh"
source "$ZDOTDIR/completion.zsh"
source "$ZDOTDIR/keybindings.zsh"
source "$ZDOTDIR/theme.zsh"
source "$ZDOTDIR/oh-my-zsh-expat/oh-my-zsh-expat.zsh"

# Load plugins
for plugin in "$ZDOTDIR/plugins/"*; do
    for file in "$plugin/"*.zsh; do
        source "$file"
    done
done
