;; necessary since there is no before workspace switch hook
(defun exwm-workspace-switch-hack (workspace)
  "Transparency reset hack function."
  (let (previous-frame (selected-frame))
    (exwm-workspace-switch workspace)
    (set-frame-parameter (previous-frame) 'alpha `(,exwm-background-transparency 0))))

;; Back to line-mode
(exwm-input-set-key (kbd "s-r") 'exwm-reset)

;; Workspace transparency
(exwm-input-set-key (kbd "s-t") 'exwm-toggle-frame-transparency)

;; Workspace keybindings
(exwm-input-set-key (kbd "s-1")
                    (lambda ()
                      (interactive)
                      (message "Workspace 0")
                      (exwm-workspace-switch 0)))
(exwm-input-set-key (kbd "s-2")
                    (lambda ()
                      (interactive)
                      (message "Workspace 1")
                      (exwm-workspace-switch 1)))
(exwm-input-set-key (kbd "s-3")
                    (lambda ()
                      (interactive)
                      (message "Workspace 2")
                      (exwm-workspace-switch 2)))
(exwm-input-set-key (kbd "s-4")
                    (lambda ()
                      (interactive)
                      (message "Workspace 3")
                      (exwm-workspace-switch 3)))
(exwm-input-set-key (kbd "s-5")
                    (lambda ()
                      (interactive)
                      (message "Workspace 4")
                      (exwm-workspace-switch 4)))
(exwm-input-set-key (kbd "s-6")
                    (lambda ()
                      (interactive)
                      (message "Workspace 5")
                      (exwm-workspace-switch 5)))
(exwm-input-set-key (kbd "s-7")
                    (lambda ()
                      (interactive)
                      (message "Workspace 6")
                      (exwm-workspace-switch 6)))
(exwm-input-set-key (kbd "s-8")
                    (lambda ()
                      (interactive)
                      (message "Workspace 7")
                      (exwm-workspace-switch 7)))
(exwm-input-set-key (kbd "s-9")
                    (lambda ()
                      (interactive)
                      (message "Workspace 8")
                      (exwm-workspace-switch 8)))

;; Application launching
(exwm-input-set-key (kbd "s-p") 'launch-application-interactively)
(exwm-input-set-key (kbd "s-<return>") (lambda ()
                                         (interactive)
                                         (launch-application "xterm")))
(exwm-input-set-key (kbd "s-s") (lambda ()
                                  (interactive)
                                  (launch-application "pass-rofi")))

;; Window switching
(exwm-input-set-key (kbd "s-i") 'windmove-up)
(exwm-input-set-key (kbd "s-j") 'windmove-left)
(exwm-input-set-key (kbd "s-k") 'windmove-right)
(exwm-input-set-key (kbd "s-m") 'windmove-down)

;; Media keys
(exwm-input-set-key (kbd "<XF86AudioRaiseVolume>") (lambda ()
                                                     (interactive)
                                                     (volume-change 5)))
(exwm-input-set-key (kbd "s-<f8>") (lambda ()
                                     (interactive)
                                     (volume-change 5)))
(exwm-input-set-key (kbd "<XF86AudioLowerVolume>") (lambda ()
                                                     (interactive)
                                                     (volume-change -5)))
(exwm-input-set-key (kbd "s-<f7>") (lambda ()
                                     (interactive)
                                     (volume-change -5)))
(exwm-input-set-key (kbd "<XF86AudioMute>") (lambda ()
                                                (interactive)
                                                (volume-mute)))
(exwm-input-set-key (kbd "s-<f6>") (lambda ()
                                     (interactive)
                                     (volume-mute)))
(exwm-input-set-key (kbd "<XF86MonBrightnessUp>") (lambda ()
                                                    (interactive)
                                                    (brightness-change 5)))
(exwm-input-set-key (kbd "<XF86MonBrightnessDown>") (lambda ()
                                                      (interactive)
                                                      (brightness-change -5)))
