# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bauer = {
    pname = "bauer";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "matthewbauer";
      repo = "bauer";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-jenFLJeVX1OlckvCv+c/u2GG8UNQatfQ8OwPu1cs4Q8=";
    };
  };
  deepfilternet = {
    pname = "deepfilternet";
    version = "v0.5.6";
    src = fetchFromGitHub {
      owner = "Rikorose";
      repo = "DeepFilterNet";
      rev = "v0.5.6";
      fetchSubmodules = false;
      sha256 = "sha256-5bYbfO1kmduNm9YV5niaaPvRIDRmPt4QOX7eKpK+sWY=";
    };
  };
  drivestrike = {
    pname = "drivestrike";
    version = "2.1.22-31";
    src = fetchurl {
      url = "https://app.drivestrike.com/static/yum/drivestrike.rpm";
      sha256 = "sha256-2O0TjRhuwLd+QPUxV9tHeuWYtGoRnBa6icU7DMmxWyI=";
    };
  };
  edopro = {
    pname = "edopro";
    version = "c40951ba09f8a8b88d1d4b9b15ca9338da01522c";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "edopro";
      rev = "c40951ba09f8a8b88d1d4b9b15ca9338da01522c";
      fetchSubmodules = true;
      sha256 = "sha256-4bNfw+H0APp+7FKsDXS6W6ypuqyDD/tLihXt9Ixk0+A=";
    };
    date = "2025-05-10";
  };
  edopro-assets = {
    pname = "edopro-assets";
    version = "41.0.2";
    src = fetchTarball {
      url = "https://github.com/ProjectIgnis/edopro-assets/releases/download/41.0.2/ProjectIgnis-EDOPro-41.0.2-linux.tar.gz";
      sha256 = "sha256-cta4k6yxrdaFFfum0eshEzLODExBfA+oVPqcOpXG9uk=";
    };
  };
  edopro-irrlicht = {
    pname = "edopro-irrlicht";
    version = "2c8b5d9a28ea5de3d69386b42d7f112f01608181";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "irrlicht1-8-4";
      rev = "2c8b5d9a28ea5de3d69386b42d7f112f01608181";
      fetchSubmodules = false;
      sha256 = "sha256-bZxTobzNdm3TACYp3uTxtiKCynRlL9CgObihFgxRMVE=";
    };
    date = "2025-05-17";
  };
  eglot-x = {
    pname = "eglot-x";
    version = "ca565df30d8e207c00471a3723d7bd5803497a95";
    src = fetchFromGitHub {
      owner = "nemethf";
      repo = "eglot-x";
      rev = "ca565df30d8e207c00471a3723d7bd5803497a95";
      fetchSubmodules = false;
      sha256 = "sha256-pJSBG84G+uRWEeoyHrsajNxIsfqlcwQM7rCsxBsn3Jc=";
    };
    date = "2025-04-19";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "v8.7.1";
    src = fetchFromGitHub {
      owner = "black7375";
      repo = "Firefox-UI-Fix";
      rev = "v8.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-2/hTy4QED2qLaMEz2gYS9IQqFf4AZACorh/8Wb2NZwA=";
    };
  };
  gcs = {
    pname = "gcs";
    version = "v5.27.0";
    src = fetchFromGitHub {
      owner = "richardwilkes";
      repo = "gcs";
      rev = "v5.27.0";
      fetchSubmodules = false;
      sha256 = "sha256-N4a+7a1XpDXsZTDiTh1AZIzXfk/A+gV4uBZdGZh+S5I=";
    };
  };
  ocgcore = {
    pname = "ocgcore";
    version = "v11.0";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "ygopro-core";
      rev = "v11.0";
      fetchSubmodules = false;
      sha256 = "sha256-q11xofN4hKg+onHxmhRz+jdBz3pcUr/Slp+RCg5cjk8=";
    };
  };
  ohmyzsh = {
    pname = "ohmyzsh";
    version = "881c8b78d3e3ade9bccfddb3e616842807d07a59";
    src = fetchFromGitHub {
      owner = "ohmyzsh";
      repo = "ohmyzsh";
      rev = "881c8b78d3e3ade9bccfddb3e616842807d07a59";
      fetchSubmodules = false;
      sha256 = "sha256-MfNt+psdgz9l0cw0X3HFHeenQz+6oV1EXnPL8T0ffGg=";
    };
    date = "2025-05-18";
  };
  phosphor-icons = {
    pname = "phosphor-icons";
    version = "00ac114a739ea7ae59287c2bf123267fdec191a5";
    src = fetchFromGitHub {
      owner = "phosphor-icons";
      repo = "web";
      rev = "00ac114a739ea7ae59287c2bf123267fdec191a5";
      fetchSubmodules = false;
      sha256 = "sha256-mHPosmdBD4ecmDUZhzPQx80z7zazmL4BiMo5K2XVXA4=";
    };
    date = "2025-05-12";
  };
}
