# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bauer = {
    pname = "bauer";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "matthewbauer";
      repo = "bauer";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-jenFLJeVX1OlckvCv+c/u2GG8UNQatfQ8OwPu1cs4Q8=";
    };
  };
  catppuccin-alacritty = {
    pname = "catppuccin-alacritty";
    version = "f6cb5a5c2b404cdaceaff193b9c52317f62c62f7";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "f6cb5a5c2b404cdaceaff193b9c52317f62c62f7";
      fetchSubmodules = false;
      sha256 = "sha256-H8bouVCS46h0DgQ+oYY8JitahQDj0V9p2cOoD4cQX+Q=";
    };
    date = "2024-10-28";
  };
  catppuccin-fuzzel = {
    pname = "catppuccin-fuzzel";
    version = "0af0e26901b60ada4b20522df739f032797b07c3";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "fuzzel";
      rev = "0af0e26901b60ada4b20522df739f032797b07c3";
      fetchSubmodules = false;
      sha256 = "sha256-XpItMGsYq4XvLT+7OJ9YRILfd/9RG1GMuO6J4hSGepg=";
    };
    date = "2024-10-30";
  };
  catppuccin-i3 = {
    pname = "catppuccin-i3";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "i3";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-91GsedHF6xM1jmutZX/xdNtGFDrGerRSaRVh29CXt8U=";
    };
  };
  delta-icons = {
    pname = "delta-icons";
    version = "v2.6.0";
    src = fetchFromGitHub {
      owner = "Delta-Icons";
      repo = "android";
      rev = "v2.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-L2QBerH6EuQQL1G3UCxyNFBSam6I+pdTrlV59XQUVVc=";
    };
  };
  edopro = {
    pname = "edopro";
    version = "90fcc7a546945f0b333e96190351e531f004298a";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "edopro";
      rev = "90fcc7a546945f0b333e96190351e531f004298a";
      fetchSubmodules = true;
      sha256 = "sha256-SLRd8z/zOAiJ/jxD1DUKVM0klMKBTy9RN3Q8n9oUCPQ=";
    };
    date = "2025-08-14";
  };
  edopro-assets = {
    pname = "edopro-assets";
    version = "41.0.2";
    src = fetchTarball {
      url = "https://github.com/ProjectIgnis/edopro-assets/releases/download/41.0.2/ProjectIgnis-EDOPro-41.0.2-linux.tar.gz";
      sha256 = "sha256-cta4k6yxrdaFFfum0eshEzLODExBfA+oVPqcOpXG9uk=";
    };
  };
  edopro-irrlicht = {
    pname = "edopro-irrlicht";
    version = "ddad09ea5e1888df424d36071558afc10d0b4f61";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "irrlicht1-8-4";
      rev = "ddad09ea5e1888df424d36071558afc10d0b4f61";
      fetchSubmodules = false;
      sha256 = "sha256-sVW1JaizN4WyCrTOezCOLyFOT3nrqUqaJAVqTR9+DrI=";
    };
    date = "2025-06-20";
  };
  eglot-x = {
    pname = "eglot-x";
    version = "8e872efd3d0b7779bde5b1e1d75c8e646a1f729f";
    src = fetchFromGitHub {
      owner = "nemethf";
      repo = "eglot-x";
      rev = "8e872efd3d0b7779bde5b1e1d75c8e646a1f729f";
      fetchSubmodules = false;
      sha256 = "sha256-a2qkitikqGZBXI4aVdn8c7P4HFwep9RPWkOVBbgQV2g=";
    };
    date = "2025-06-26";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "v8.7.3";
    src = fetchFromGitHub {
      owner = "black7375";
      repo = "Firefox-UI-Fix";
      rev = "v8.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-2AIUzfWp7RhhW5Ku1qYTxr0y+1qpfCIHPVv3wdI2VyU=";
    };
  };
  gcs = {
    pname = "gcs";
    version = "v5.27.0";
    src = fetchFromGitHub {
      owner = "richardwilkes";
      repo = "gcs";
      rev = "v5.27.0";
      fetchSubmodules = false;
      sha256 = "sha256-N4a+7a1XpDXsZTDiTh1AZIzXfk/A+gV4uBZdGZh+S5I=";
    };
  };
  kdl-mode = {
    pname = "kdl-mode";
    version = "2d849e298199f490e4894c01764a8a83decd704a";
    src = fetchFromGitHub {
      owner = "taquangtrung";
      repo = "emacs-kdl-mode";
      rev = "2d849e298199f490e4894c01764a8a83decd704a";
      fetchSubmodules = false;
      sha256 = "sha256-5PHAV1yrpiZrWJDI5r9dSgfbSJQJ80nQXvklr24saqM=";
    };
    date = "2025-06-20";
  };
  nvidia = {
    pname = "nvidia";
    version = "580.76.05";
    src = fetchurl {
      url = "https://us.download.nvidia.com/XFree86/Linux-x86_64/580.76.05/NVIDIA-Linux-x86_64-580.76.05.run";
      sha256 = "sha256-IZvmNrYJMbAhsujB4O/4hzY8cx+KlAyqh7zAVNBdl/0=";
    };
  };
  nvidia-open = {
    pname = "nvidia-open";
    version = "580.76.05";
    src = fetchFromGitHub {
      owner = "NVIDIA";
      repo = "open-gpu-kernel-modules";
      rev = "580.76.05";
      fetchSubmodules = false;
      sha256 = "sha256-xEPJ9nskN1kISnSbfBigVaO6Mw03wyHebqQOQmUg/eQ=";
    };
  };
  ocgcore = {
    pname = "ocgcore";
    version = "v11.0";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "ygopro-core";
      rev = "v11.0";
      fetchSubmodules = false;
      sha256 = "sha256-q11xofN4hKg+onHxmhRz+jdBz3pcUr/Slp+RCg5cjk8=";
    };
  };
  phosphor-icons = {
    pname = "phosphor-icons";
    version = "00ac114a739ea7ae59287c2bf123267fdec191a5";
    src = fetchFromGitHub {
      owner = "phosphor-icons";
      repo = "web";
      rev = "00ac114a739ea7ae59287c2bf123267fdec191a5";
      fetchSubmodules = false;
      sha256 = "sha256-mHPosmdBD4ecmDUZhzPQx80z7zazmL4BiMo5K2XVXA4=";
    };
    date = "2025-05-12";
  };
}
