# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bauer = {
    pname = "bauer";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "matthewbauer";
      repo = "bauer";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-jenFLJeVX1OlckvCv+c/u2GG8UNQatfQ8OwPu1cs4Q8=";
    };
  };
  deepfilternet = {
    pname = "deepfilternet";
    version = "v0.5.6";
    src = fetchFromGitHub {
      owner = "Rikorose";
      repo = "DeepFilterNet";
      rev = "v0.5.6";
      fetchSubmodules = false;
      sha256 = "sha256-5bYbfO1kmduNm9YV5niaaPvRIDRmPt4QOX7eKpK+sWY=";
    };
  };
  drivestrike = {
    pname = "drivestrike";
    version = "2.1.22-31";
    src = fetchurl {
      url = "https://app.drivestrike.com/static/yum/drivestrike.rpm";
      sha256 = "sha256-2O0TjRhuwLd+QPUxV9tHeuWYtGoRnBa6icU7DMmxWyI=";
    };
  };
  edopro = {
    pname = "edopro";
    version = "473af98e3f5eb015a2b481481abbcc8c8027b484";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "edopro";
      rev = "473af98e3f5eb015a2b481481abbcc8c8027b484";
      fetchSubmodules = true;
      sha256 = "sha256-orAFzOHPrJ4BzQ+6sBljkiBZjbSSPiIelH12fdytRT4=";
    };
    date = "2024-07-18";
  };
  edopro-assets = {
    pname = "edopro-assets";
    version = "40.1.4";
    src = fetchTarball {
      url = "https://github.com/ProjectIgnis/edopro-assets/releases/download/40.1.4/ProjectIgnis-EDOPro-40.1.4-linux.tar.gz";
      sha256 = "sha256-vZhkWJ1ZoNEwdc5kM1S0hyXnWmupiTOanCi9DCuqw/k=";
    };
  };
  edopro-irrlicht = {
    pname = "edopro-irrlicht";
    version = "ba76104ccb104d769cdccda014e0a3966f7c40ac";
    src = fetchFromGitHub {
      owner = "edo9300";
      repo = "irrlicht1-8-4";
      rev = "ba76104ccb104d769cdccda014e0a3966f7c40ac";
      fetchSubmodules = false;
      sha256 = "sha256-xVlVt9zv7SenEYhBQSop4UnNS5g4N5aPgiqSHhhajD8=";
    };
    date = "2024-03-16";
  };
  eglot-x = {
    pname = "eglot-x";
    version = "34eb04fcd456158f486b59f4e3b3ad8f95f9fbaa";
    src = fetchFromGitHub {
      owner = "nemethf";
      repo = "eglot-x";
      rev = "34eb04fcd456158f486b59f4e3b3ad8f95f9fbaa";
      fetchSubmodules = false;
      sha256 = "sha256-/YXoZhySujtQhcmi74Tdv7Hp/DAz5UEnujUcucusMzg=";
    };
    date = "2024-07-30";
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "v8.6.2";
    src = fetchFromGitHub {
      owner = "black7375";
      repo = "Firefox-UI-Fix";
      rev = "v8.6.2";
      fetchSubmodules = false;
      sha256 = "sha256-19aivAOvXeFOnsP5XhitK3+xk1lwUyXoTK8BE84qbFQ=";
    };
  };
  gauth = {
    pname = "gauth";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "pcarrier";
      repo = "gauth";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-GU6HKha7Y01HJX6pyYHORUkFKgl9mWtDd65d+3pYxjI=";
    };
  };
  gcs = {
    pname = "gcs";
    version = "v5.26.0";
    src = fetchFromGitHub {
      owner = "richardwilkes";
      repo = "gcs";
      rev = "v5.26.0";
      fetchSubmodules = false;
      sha256 = "sha256-ZXC0LHdkeibXYdjQ3HZ76cT0cMARdSe/z++nfIzfF08=";
    };
  };
  ohmyzsh = {
    pname = "ohmyzsh";
    version = "01a955657408c8396fc947075a912ee868d5e2a7";
    src = fetchFromGitHub {
      owner = "ohmyzsh";
      repo = "ohmyzsh";
      rev = "01a955657408c8396fc947075a912ee868d5e2a7";
      fetchSubmodules = false;
      sha256 = "sha256-eL+pXfC0jzwb+BszCvFVls7orMijFtv35E2X2zY/NbI=";
    };
    date = "2024-07-28";
  };
  phosphor-icons = {
    pname = "phosphor-icons";
    version = "9634e6f3bccabbc1bf2c59dc283abd283d00946d";
    src = fetchFromGitHub {
      owner = "phosphor-icons";
      repo = "web";
      rev = "9634e6f3bccabbc1bf2c59dc283abd283d00946d";
      fetchSubmodules = false;
      sha256 = "sha256-Ul0UtnsrJ4pUY+rozU7W6DIpIq7DstQN69sOql4x6Yc=";
    };
    date = "2024-05-02";
  };
  tridactyl-emacs = {
    pname = "tridactyl-emacs";
    version = "ee82f3de875e7cda518cfd2c469ec21ed94c3cfb";
    src = fetchFromGitHub {
      owner = "jumper047";
      repo = "tridactyl_emacs_config";
      rev = "ee82f3de875e7cda518cfd2c469ec21ed94c3cfb";
      fetchSubmodules = false;
      sha256 = "sha256-OGSVKUoZ9E5yqJQfTnfx6QW4vLbdQ5/V3VX65TuQG4k=";
    };
    date = "2023-12-22";
  };
}
