[package]
name = "desktop-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
zbus = "5.11.0"
thiserror = "2.0.16"
nix = "0.30.1"
tokio = { version = "1.47.1", features = ["macros", "rt", "rt-multi-thread", "sync"] }
