# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  bauer = {
    pname = "bauer";
    version = "v1.5.3";
    src = fetchgit {
      url = "https://github.com/matthewbauer/bauer";
      rev = "v1.5.3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "14k1nzjrgl8ppm785v32h4bi11248y194mjpblqym5hjc3nxf710";
    };
    
  };
  firefox-ui-fix = {
    pname = "firefox-ui-fix";
    version = "ed437e953a85ac2087e391cfc41037dcb0b81bd1";
    src = fetchgit {
      url = "https://github.com/black7375/Firefox-UI-Fix";
      rev = "ed437e953a85ac2087e391cfc41037dcb0b81bd1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "136y65956jb23afgnq028s0ih6zvigpcjk1br0b8g756ida1zpcb";
    };
  };
  gauth = {
    pname = "gauth";
    version = "v1.1";
    src = fetchgit {
      url = "https://github.com/pcarrier/gauth";
      rev = "v1.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "179jxp2n6bms0x5brqyhd1437d5gfh75jn3sl0m7d04jf3kk3bi1";
    };
    
  };
  gcs = {
    pname = "gcs";
    version = "v4.34.1";
    src = fetchgit {
      url = "https://github.com/richardwilkes/gcs";
      rev = "v4.34.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "19zy7kbsdhxh3n659qvivv2qnna43zkiypdnag8z8d99srvycwh9";
    };
  };
  ohmyzsh = {
    pname = "ohmyzsh";
    version = "1c9a64ece6dce901aac114deaa71b298a32fbfb4";
    src = fetchgit {
      url = "https://github.com/ohmyzsh/ohmyzsh";
      rev = "1c9a64ece6dce901aac114deaa71b298a32fbfb4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1w8qywxzggd1pgmvsam6afirvgk4ppi1sdqp2bfblyyk68qgdidr";
    };
  };
  stumpwm-contrib = {
    pname = "stumpwm-contrib";
    version = "d3101d72c350046962194b4fd408e7b5d908fb8f";
    src = fetchgit {
      url = "https://github.com/stumpwm/stumpwm-contrib";
      rev = "d3101d72c350046962194b4fd408e7b5d908fb8f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1sb1nbiaxavfi73f24q12r5pgk6wll78rabnn8ywqhjisavl2gl6";
    };
  };
  tridactyl-emacs = {
    pname = "tridactyl-emacs";
    version = "abc05ae33d282dc8fb999f0706efe406766ed9dc";
    src = fetchgit {
      url = "https://github.com/jumper047/tridactyl_emacs_config";
      rev = "abc05ae33d282dc8fb999f0706efe406766ed9dc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0gmp55kbdrhmdfdzij07jpblqgw6badfnsjgqxfrkhwdwkcgzm5r";
    };
  };
  zsh-background-notify = {
    pname = "zsh-background-notify";
    version = "d5f0430cb052f82c433c17707816910da87e201e";
    src = fetchgit {
      url = "https://github.com/t413/zsh-background-notify";
      rev = "d5f0430cb052f82c433c17707816910da87e201e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0p8fk50bxr8kg2v72afg7f2n09n9ap0yn7gz1i78nd54l0wc041n";
    };
    
  };
}
