name: check
on: push
jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix flake check -L
