name: check
on: push
jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
      - run: |
          nix flake check -L
          # Also run tests with nixos-hosts, so that we assert the
          # actual system config resolves - `homeConfigurations` are
          # currently not covered by `nix flake check`
          nix flake check \
              --no-write-lock-file \
              --override-input dotfiles "$(pwd)" \
              'github:tlater/nixos-hosts'
