name: lint
on: push
jobs:
  format:
    name: Check nix file format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: |
          find . -path ./dotfiles/emacs.d/share/yatemplate -prune \
                 -type f -name '*.nix' \
                 ! -name 'hardware-configuration.nix' \
                 ! -name 'generated.nix' \
                 -exec nix run nixpkgs#nixfmt -- -c {} +

  check:
    name: Check nix correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: |
          nix build .#gcs

          nix flake check \
              --no-write-lock-file \
              --override-input dotfiles "$(pwd)" \
              'github:tlater/nixos-hosts'
