name: lint
on: push
jobs:
  format:
    name: Check nix file format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
      - run: |
          nix run --inputs-from .# alejandra -- \
              --check \
              --exclude ./dotfiles/emacs.d/share/yatemplate/ \
              --exclude ./nixpkgs/pkgs/_sources/ \
              .

  check:
    name: Check nix correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
      - run: |
          nix build .#gcs

          nix flake check \
              --no-write-lock-file \
              --override-input dotfiles "$(pwd)" \
              'github:tlater/nixos-hosts'
