name: update
on:
  schedule:
    - cron: '0 2 * * 6'
  workflow_dispatch:
jobs:
  update:
    name: Update flake inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PR_CREATE_KEY }}
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          # Used only for things like nix-prefetch-*, which do not yet
          # seem to universally support flakes
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GIT_SIGNING_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: GitHub automation
          git_committer_email: tm@tlater.net
      - run: nix flake update --commit-lock-file
      - run: |
          echo -e '[keys]\ngithub = "${{ secrets.GITHUB_TOKEN }}"' > /tmp/github-key.toml
          nix run .#commit-nvfetcher -L
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/update
          delete-branch: true
          title: Update flake inputs
